# Generated by Django 2.0.1 on 2018-04-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_sponsorship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='content_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('listing_text_en', 'Listing Text (English)'), ('listing_text_he', 'Listing Text (Hebrew)')], default='simple', max_length=20, verbose_name='content type'),
        ),
    ]
