# Generated by Django 2.0.1 on 2018-03-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_speakers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='financial_assistance',
            field=models.BooleanField(default=False, verbose_name='Financial Assistance Needed?'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Phone number'),
        ),
    ]
