# Generated by Django 2.0.4 on 2018-04-14 23:34

from django.db import migrations, models
import ilpycon.dbfiles.storage


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_speakers', '0002_auto_20180316_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(blank=True, storage=ilpycon.dbfiles.storage.DBFilesStorage('default'), upload_to='speaker_photos', verbose_name='Photo'),
        ),
    ]
