# Generated by Django 2.0.1 on 2018-03-16 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Target Audience',
                'verbose_name_plural': 'Target Audiences',
            },
        ),
        migrations.AddField(
            model_name='talkproposal',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(0, 1500), 'Standard 25 minutes talk.'), (datetime.timedelta(0, 2400), 'Long 40 minutes talk.'), (datetime.timedelta(0, 12600), 'Half day workshop/sprint (3.5 hours net).'), (datetime.timedelta(0, 25200), 'Full day workshop/sprint (7 hours net).')], default=datetime.timedelta(0, 1500), verbose_name='Session Duration'),
        ),
        migrations.AddField(
            model_name='talkproposal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('he', 'Hebrew')], default='en', max_length=5, verbose_name='Proposal Language'),
        ),
        migrations.AddField(
            model_name='talkproposal',
            name='second_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('he', 'Hebrew')], max_length=5, verbose_name='Propsal Lanugauge - 2nd choice'),
        ),
        migrations.AddField(
            model_name='talkproposal',
            name='specific_props',
            field=models.CharField(blank=True, help_text='Any Specific Props Needed?', max_length=200, verbose_name='Specific Props'),
        ),
        migrations.AddField(
            model_name='talkproposal',
            name='target_audience_other',
            field=models.CharField(blank=True, max_length=200, verbose_name='Other target audience'),
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(0, 1500), 'Standard 25 minutes talk.'), (datetime.timedelta(0, 2400), 'Long 40 minutes talk.'), (datetime.timedelta(0, 12600), 'Half day workshop/sprint (3.5 hours net).'), (datetime.timedelta(0, 25200), 'Full day workshop/sprint (7 hours net).')], default=datetime.timedelta(0, 1500), verbose_name='Session Duration'),
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('he', 'Hebrew')], default='en', max_length=5, verbose_name='Proposal Language'),
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='second_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('he', 'Hebrew')], max_length=5, verbose_name='Propsal Lanugauge - 2nd choice'),
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='specific_props',
            field=models.CharField(blank=True, help_text='Any Specific Props Needed?', max_length=200, verbose_name='Specific Props'),
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='target_audience_other',
            field=models.CharField(blank=True, max_length=200, verbose_name='Other target audience'),
        ),
        migrations.AddField(
            model_name='talkproposal',
            name='target_audience',
            field=models.ManyToManyField(related_name='talkproposals', to='proposals.TargetAudience', verbose_name='Target Audience'),
        ),
        migrations.AddField(
            model_name='tutorialproposal',
            name='target_audience',
            field=models.ManyToManyField(related_name='tutorialproposals', to='proposals.TargetAudience', verbose_name='Target Audience'),
        ),
    ]
